# Generated by Django 4.2.7 on 2023-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
