# Generated by Django 4.2.7 on 2023-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_category_image_alter_language_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/'),
        ),
    ]
